Repository AY2324S1-CS2103T-W10-3/tp, pull requests merged in 2023-10, with the labels that each got.

#56 Update several formatting issues in DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.Docs

#57 Add AddDentistCommand, including Storage and GUI
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddDentistCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/AddDentistCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/dentist/Dentist.java
  src/main/java/seedu/address/model/person/dentist/Specialization.java
  src/main/java/seedu/address/model/person/dentist/UniqueDentistList.java
  src/main/java/seedu/address/model/person/dentist/Yoe.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDentist.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/DentistCard.java
  src/main/java/seedu/address/ui/DentistListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DentistListCard.fxml
  src/main/resources/view/DentistListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, type.Story, priority.High

#62 Critical bug fix: Fix bug whereby reloading application results in failure to load json
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: bug

#65 Dentist ID Implementation
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddDentistCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/dentist/Dentist.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDentist.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/DentistCard.java
  src/main/resources/view/DentistListCard.fxml
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, priority.High

#66 Add in else statement to fix duplicate dentist add
  src/main/java/seedu/address/model/AddressBook.java
Labels: bug

#123 Update ToothTracker Model Class Diagram and Description in DG
  docs/DeveloperGuide.md
  docs/diagrams/ToothTrackerModelClassDiagram.puml
  docs/images/ToothTrackerModelClassDiagram.png
Labels: type.Docs

#126 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteDentistSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Docs

#127 Update DG on Manual Testing for Dentist features
  docs/DeveloperGuide.md
Labels: type.Docs

#141 Implement Recognized Specialization
  src/main/java/seedu/address/model/person/dentist/Specialization.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteDentistCommandTest.java
  src/test/java/seedu/address/testutil/DentistBuilder.java
  src/test/java/seedu/address/testutil/TypicalDentists.java
Labels: enhancement, prority.Medium
